version: "3.7"

services:
  {{SERVICE.DATABASE.NAME}}:
    image: library/postgres:13
    container_name: {{SERVICE.DATABASE.NAME}}
    hostname: database.{{SERVER.DOMAIN}}
    restart: always
    ports:
      - 127.0.0.1:{{SERVICE.DATABASE.PORTS.PORT_EXPOSED}}:{{SERVICE.DATABASE.PORTS.PORT}}
    networks:
      - {{SERVICE.NETWORK.NAME}}
    environment:
      POSTGRES_USER: {{SERVICE.DATABASE.USER}}
      POSTGRES_PASSWORD: {{SERVICE.DATABASE.PASSWORD}}
      PGDATA: /Server/Postgres/Database
    volumes:
      - {{SERVER.SERVER_HOME}}/Server/Postgres/Database:/Server/Postgres/Database

networks:
  {{SERVICE.NETWORK.NAME}}:
    external: true



